### ISSUE TITLE
Stationsnamn får inte innehålla kommatecken

### ISSUE THREAD

**Issue by MartinHanssonSMHI** [sharksmhi/SHARKtools_pre_system_Svea#6]
Hej! 

Kontrollera inskrivet stationsnamn (tex extrastation eller fiskestation) om det innehåller kommatecken (,) och omvandla det till punkt. 

Kommatecken i statationsnamnet ställer till det i tex LIMS, som då läster in fel från std-formatet. I std-formatet ligger stationsnamet på varje rad i data därav problemet.

**Comment by magnuswenzerSMHI** [comment]
Byter ut komma mot punkt när man startar seasave. dvs det kommer inte synas i stations-fältet. Det vär lättast så. Är det ok? @MartinHanssonSMHI
